name: 'Bobs '
favicon: null
layout_spectrum: 0.4697641914244741
typography_spectrum: 0.7834300592076033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1332023348659277
  lightness: 0.7028130334801972
  saturation: 0.6029618114698678
  rhythmicContrast: 0.4007824643049389
purpose: []
